config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  
  resources :recipes do
    resources :comments, only: [:create]
    member do 
      post 'like'
    end
  end
  
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :ingredients, except: [:destroy]
  
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'
  
  resources :messages, only: [:create]
  
end

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>Welcome to MyRecipes</h1>
  <h2>The best recipe sharing app!</h2>
  <p><%= link_to "Sign up for the app", signup_path, class: "btn btn-danger btn-lg btn-xlarge" %></p>
</div>

<div class="row">
  <div class="col-lg-4">
    <h2>Explore Recipes</h2>
    <p>We have a ton of recipes for you to explore, not sure about the app yet? Don't worry just view as a guest, we're sure you'll come back to sign-up at a later time</p>
    <p><%= link_to "View all recipes as a Guest!", recipes_path, class: "btn btn-primary btn-xlarge" %></p>
  </div>
  <div class="col-lg-4">
    <h2>Unlock all features!</h2>
    <p>Sign up for the app and unlock all it's magic, create and share recipes, hangout with chefs in the chefchat, comment on recipes you have tried out, like/dislike and much much more!</p>
    <p><%= link_to "Sign up for an account", signup_path, class: "btn btn-primary btn-xlarge" %></p>
 </div>
  <div class="col-lg-4">
    <h2>Have an ingredient, need ideas?</h2>
    <p>View our ingredients listing page and select an ingredient that you have to view recipes associated with it for cooking ideas!</p>
    <p><%= link_to "View ingredients listing", ingredients_path, class: "btn btn-primary btn-xlarge" %></p>
  </div>
</div>